/**
 * Single source of truth: package.json "version".
 * Writes version to:
 *   - src-tauri/tauri.conf.json
 *   - src-tauri/Cargo.toml
 *   - src/lib/version.generated.ts (for app UI)
 * Run before build/dev so all surfaces show the same version.
 */
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const pkgPath = path.join(ROOT, "package.json");
const tauriConfPath = path.join(ROOT, "src-tauri", "tauri.conf.json");
const cargoPath = path.join(ROOT, "src-tauri", "Cargo.toml");
const generatedPath = path.join(ROOT, "src", "lib", "version.generated.ts");

const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
const version = pkg.version;
if (!version || typeof version !== "string") {
  console.error("package.json must have a string 'version'");
  process.exit(1);
}

// tauri.conf.json
if (fs.existsSync(tauriConfPath)) {
  const tauri = JSON.parse(fs.readFileSync(tauriConfPath, "utf8"));
  tauri.version = version;
  fs.writeFileSync(tauriConfPath, JSON.stringify(tauri, null, 2) + "\n", "utf8");
  console.log("Updated src-tauri/tauri.conf.json version:", version);
}

// Cargo.toml – replace first [package] version = "..." line
if (fs.existsSync(cargoPath)) {
  let cargo = fs.readFileSync(cargoPath, "utf8");
  cargo = cargo.replace(/^version\s*=\s*"[^"]*"/m, `version = "${version}"`);
  fs.writeFileSync(cargoPath, cargo, "utf8");
  console.log("Updated src-tauri/Cargo.toml version:", version);
}

// Frontend: generated module so UI can import APP_VERSION
const dir = path.dirname(generatedPath);
if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
const generated = `/** Generated by scripts/sync-version.cjs - do not edit. Source of truth: package.json version. */
export const APP_VERSION = ${JSON.stringify(version)};
`;
fs.writeFileSync(generatedPath, generated, "utf8");
console.log("Updated src/lib/version.generated.ts APP_VERSION:", version);
